apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: k8s-network-policy
  namespace: k8s-dev
spec:
  podSelector:
    matchLabels:
      app: ratingsapi-pod
  policyTypes:
  - Ingress
  ingress:
  - from:    
    - namespaceSelector:
        matchLabels:
          name: k8s-dev
    - podSelector:
        matchLabels:
          app: ratingsweb-pod    